version: '3.9'

services:
  frontend:
    build: 
      context: ../frontend
    ports:
      - "3001:80"
    environment:
      - REACT_API_URL=${API_URL}

  backend:
    build:
      context: ../backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "3000:3000"

  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"  
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:  